# Generated by Django 5.0.1 on 2025-10-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('mechanism', models.TextField(verbose_name='Cơ chế dân chủ áp dụng')),
                ('pros', models.TextField(blank=True, verbose_name='Ưu điểm')),
                ('cons', models.TextField(blank=True, verbose_name='Hạn chế')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Ví dụ: 21.028511', max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Ví dụ: 105.804817', max_digits=9, verbose_name='Kinh độ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL hình ảnh')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
