# Generated by Django 5.0.1 on 2025-10-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('infographic', 'Infographic'), ('story', 'Story')], default='text', max_length=20, verbose_name='Loại media')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL media')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Phần lý thuyết',
                'verbose_name_plural': 'Các phần lý thuyết',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
