# Generated by Django 5.0.1 on 2025-10-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint (user, post)
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        # Step 2: Remove ForeignKey fields
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        # Step 3: Add new CharField fields
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Người dùng ẩn danh', help_text='Tên người bình luận', max_length=100, verbose_name='Họ và tên tác giả'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Người dùng ẩn danh', help_text='Tên người đăng bài', max_length=100, verbose_name='Họ và tên tác giả'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='session_key',
            field=models.CharField(default='migrated_vote', help_text='Session ID hoặc identifier của người vote', max_length=100, verbose_name='Session Key'),
            preserve_default=False,
        ),
        # Step 4: Add new unique_together constraint (session_key, post)
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('session_key', 'post')},
        ),
    ]
